version: '3'
services:
  movies:
    image: niroopa12/paytm1-movies:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3
  train:
    image: niroopa12/paytm2-train:latest
    ports:
      - "95:80"
    deploy:
      replicas: 3
  recharge:
    image: niroopa12/paytm3-recharge:latest
    ports:
      - "96:80"
    deploy:
      replicas: 3
  dth:
    image: niroopa12/paytm4-dth:latest
    ports:
      - "97:80"
    deploy:
      replicas: 3
