version: '3'
services:
  movies:
    image: niroopa12/paytm-movies:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3
  train:
    image: niroopa12/paytm-train:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  recharge:
    image: niroopa12/paytm-recharge:latest
    deploy:
      replicas: 3
  dth:
    image: niroopa12/paytm-dth:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
